#!/bin/bash

# chkconfig: 2345 90 20
# description: Provides TBTaskd service

### BEGIN INIT INFO
# Provides:          TBTaskd
# Required-Start:    $all
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Starts the TreasureBoat Task Daemon
# Description:       Starts the TreasureBoat Task Daemon which is necessary to
#       			 run TreasureBoat Applications at this host. TreasureBoat Task Daemon
#       			 needs to run to be an configurable host via TreasureBoat Monitor.
### END INIT INFO

USER=appserver
GROUP=appserveradm
NEXT_ROOT="/opt"
export NEXT_ROOT
TIME="[`date +%d.%m.%Y\ %H:%M:%S`]:"
LOGFILE=/opt/Local/Library/WebObjects/Logs/tbtaskd.log

###############################################################################

# Create Logfile if not already exists and setup permissions.
if [ ! -e "$LOGFILE" ]; then
    touch "$LOGFILE"
    chown $USER:$GROUP "$LOGFILE"
    chmod 640 "$LOGFILE"
fi

# Create Logroate Job if available.
if [ -e "/etc/logrotate.d" ] && [ ! -e "/etc/logrotate.d/tbtaskd" ]; then
    echo "$LOGFILE {"               > /etc/logrotate.d/tbtaskd
    echo "    su $USER $GROUP"      >> /etc/logrotate.d/tbtaskd
    echo '    daily'                >> /etc/logrotate.d/tbtaskd
    echo '    rotate 5'             >> /etc/logrotate.d/tbtaskd
    echo '    compress'             >> /etc/logrotate.d/tbtaskd
    echo '    delaycompress'        >> /etc/logrotate.d/tbtaskd
    echo '    missingok'            >> /etc/logrotate.d/tbtaskd
    echo '    notifempty'           >> /etc/logrotate.d/tbtaskd
    echo '}'                        >> /etc/logrotate.d/tbtaskd
fi

###############################################################################

# See how we were called.
case "$1" in
    status)
        TBTASKD_PID=`ps aux | awk '/TBPort 1085/ && !/awk/ {print $2}'`
        if [ "$TBTASKD_PID" != "" ]; then
            echo "$TIME Service is running with PID $TBTASKD_PID" 2>&1 | tee -a $LOGFILE
        else
            echo "$TIME Service is not running" 2>&1 | tee -a $LOGFILE
        fi
        ;;
    start)
        echo "$TIME Starting tbtaskd: " 2>&1 | tee -a $LOGFILE
#        su $USER -c -l "$NEXT_ROOT/TreasureBoat/Applications/tbtaskd.woa/tbtaskd -p 1085 -newPath -url 2>&1 | tee -a $LOGFILE &"       
       su $USER -c -l "$NEXT_ROOT/Local/Library/WebObjects/Applications/tbtaskd.woa/tbtaskd -p 1085 -h [myhost_name] 2>&1 | tee -a $LOGFILE &"
        ;;
    stop)
        echo "$TIME Shutting down TBTaskd" 2>&1 | tee -a $LOGFILE
        TBTASKD_PID=`ps aux | awk '/TBPort 1085/ && !/awk/ {print $2}'`
        kill $TBTASKD_PID
        ;;
    restart)
        $0 stop
        $0 start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|status}"
        exit 1
esac

if [ $# -gt 1 ]; then
    shift
    $0 $*
fi

exit 0
