mainClassName = 'org.treasureboat.app.tbtaskd.Application'

dependencies {
	// https://mvnrepository.com/artifact/org.projectlombok/lombok
	implementation("org.projectlombok:lombok:1.18.38")


	compile "org.treasureboat:tb-core-extensions:10.1.5"
	compile "org.treasureboat:tb-features-rest:10.1.9"
	compile "org.treasureboat:tb-extra-monitor:10.1.1"
	    
	compile 'org.apache.mina:mina-core:2.0.4'
	compile 'org.apache.sshd:sshd-pam:0.7.0'
	compile 'org.apache.sshd:sshd-core:0.7.0'
    
}
