#!/usr/bin/env python3
"""Regenerate tb-schema-audit.sql from the live .eomodeld models.

Run from GitRoot. Re-run whenever a model changes -- the expected table/column
list is only as current as the models it was built from.
"""
import re, pathlib, collections, sys

ROOT = pathlib.Path(sys.argv[1] if len(sys.argv) > 1 else ".")
MODELS = [
 ("basemodel","treasureboat-features/tb-features-basemodel/src/main/resources/TBBaseModel.eomodeld"),
 ("cms","treasureboat-pro/tb-pro-cms/src/main/resources/TBCMS.eomodeld"),
 ("nc","treasureboat-pro/tb-pro-notification-center/src/main/resources/TBNC.eomodeld"),
 ("nc_mailinglist","treasureboat-pro/tb-pro-notification-center/src/main/resources/TBNC_MailingList.eomodeld"),
 ("nc_communication","treasureboat-pro/tb-pro-notification-center/src/main/resources/TBNC_Communication.eomodeld"),
 ("nc_pool","treasureboat-pro/tb-pro-notification-center/src/main/resources/TBNC_Pool.eomodeld"),
 ("nc_massmail","treasureboat-pro/tb-pro-notification-center/src/main/resources/TBNC_MassMail.eomodeld"),
 ("ruleengine","treasureboat-pro/tb-pro-rule-engine/src/main/resources/tb_pro_rule_engine_model.eomodeld"),
 ("businesslicense","treasureboat-ultra/tb-ultra-business-license/src/main/resources/TBBusinessLicenseModel.eomodeld"),
 ("distribution","treasureboat-ultra/tb-ultra-distribution/src/main/resources/tb_ultra_distribution_model.eomodeld"),
]
ext_re = re.compile(r'externalName\s*=\s*("([^"]+)"|([A-Za-z_][\w]*))\s*;')
col_re = re.compile(r'columnName\s*=\s*("([^"]+)"|([A-Za-z_][\w]*))\s*;')

tables, owners = collections.defaultdict(set), collections.defaultdict(set)
colowners = collections.defaultdict(set)   # (table, column) -> contributing models
for model, rel in MODELS:
    d = ROOT / rel
    if not d.is_dir():
        print(f"  !! model not found, skipped: {rel}"); continue
    for f in sorted(d.glob("*.plist")):
        s = f.read_text(errors="replace")
        m = ext_re.search(s)
        if not m: continue
        tbl = m.group(2) or m.group(3)
        cols = {(c.group(2) or c.group(3)) for c in col_re.finditer(s)}
        tables[tbl] |= cols
        owners[tbl].add(model)
        for c in cols:
            colowners[(tbl, c)].add(model)   # partials contribute to another model's table

def q(s): return "'" + s.replace("'", "''") + "'"
tbl_rows = ",\n  ".join("(%s,%s)" % (q(t), q(",".join(sorted(owners[t])))) for t in sorted(tables))
col_rows = ",\n  ".join("(%s,%s,%s)" % (q(t), q(c), q(",".join(sorted(colowners[(t, c)]))))
                        for t in sorted(tables) for c in sorted(tables[t]))

LEFTOVER = [("tb_cms_SurveyData","TBCMS10","drop"),("tb_cms_SurveyResponse","TBCMS10","drop"),
 ("tb_nc_EmailClient","TBNC8","drop"),("tb_nc_MassMailDelivery","TBNC11","drop"),
 ("tb_nc_MassMailRequest","TBNC11","drop"),("tb_re_EventReject","rule_engine_model2","drop"),
 ("tb_re_EventAccept","rule_engine_model2","drop"),("tb_re_WorkingStack","rule_engine_model2","drop"),
 ("tb_re_Event","rule_engine_model2","drop"),("tb_re_EventGroup","rule_engine_model2","drop"),
 ("tb_nc_Newsletter","TBNC9","rename -> deprecated_nc_Newsletter"),
 ("tb_nc_MailTemplate","TBNC10","rename -> deprecated_nc_MailTemplate"),
 ("tb_nc_MailTemplateForLocalize","TBNC10","rename -> deprecated_nc_MailTemplateForLocalize"),
 ("tb_nc_MailGroup","TBNC12","rename -> deprecated_nc_MailGroup"),
 ("tb_nc_MailGroupMailRecipient","TBNC12","rename -> deprecated_nc_MailGroupMailRecipient"),
 ("tb_nc_MailRecipient","TBNC12","rename -> deprecated_nc_MailRecipient"),
 ("TBServerLicense","tb_ultra_distribution_model13","rename -> tb_dis_ServerLicense"),
 ("TBServerMatchList","tb_ultra_distribution_model13","rename -> tb_dis_ServerVideoMatch"),
 ("tb_bm_navigationFavorite","TBBaseModel29","rename -> tb_bm_NavigationFavorite")]
LEFTCOL = [("tb_bm_Person","defaultLanguage","TBBaseModel18"),
 ("tb_bl_BusinessLicenseCustomer","address","TBBusinessLicenseModel11"),
 ("tb_bl_BusinessLicenseCustomer","homeBased","TBBusinessLicenseModel11"),
 ("tb_bl_BusinessLicenseCustomer","street","TBBusinessLicenseModel11"),
 ("tb_bl_BusinessLicenseCustomer","zone","TBBusinessLicenseModel11"),
 ("tb_bl_BusinessLicense","city","TBBusinessLicenseModel13"),
 ("tb_bl_BusinessLicense","province","TBBusinessLicenseModel13"),
 ("tb_bl_BusinessLicense","zip","TBBusinessLicenseModel13")]
left_rows = ",\n  ".join("(%s,%s,%s)" % (q(t), q(m), q(w)) for t, m, w in LEFTOVER)
leftcol_rows = ",\n  ".join("(%s,%s,%s)" % (q(t), q(c), q(m)) for t, c, m in LEFTCOL)

sql = f"""-- ============================================================================
-- TreasureBoat schema audit -- PostgreSQL, READ-ONLY (no writes, no DDL)
-- Generated by gen-tb-schema-audit.py from the .eomodeld models.
-- REGENERATE after any model change, or removed entities show as false gaps.
--
-- Why: @TBEnterpriseMigrationSkipError rolled back inside a finally, so the
-- rollback fired on SUCCESS as well as failure. Annotated migrations discarded
-- their own completed work while the version advanced, and logged nothing,
-- because nothing had failed. Fixed in tb-core 2b7aa658.
--
-- READING SECTION 1: a framework the app does not install shows ALL its tables
-- missing -- not damage. Damage is SOME tables of a model missing.
--
-- READING SECTION 2: the detail column names the model that WANTS the column.
-- A partial entity can contribute columns to another framework's table (e.g.
-- distribution's TBServerPerson adds company/about/gitHub/idTBServerLicense to
-- basemodel's tb_bm_Person). If that model is not installed here, those columns
-- are absent legitimately. Cross-check against section 1: if the same model's
-- own tables are all missing, it is not installed, and its columns are not
-- damage either.
--
-- NOTE this client may run AUTOCOMMIT OFF. This file is read-only so it does
-- not matter here, but never verify a WRITE from the same session that made it.
--
-- ---------------------------------------------------------------------------
-- SET THE SCHEMA FIRST. The audit reads the session search_path, so pointing it
-- at the wrong schema reports EVERY table as missing -- a total false alarm.
--
--     AppGWare   gw_fist            -> public
--     Edison     es_pg_lake         -> public
--     Edison     es_pg_cscw         -> public
--     Boise      fft_prod_bak2_pg   -> fft_prod_bak2     <-- NOT public
--
-- Edison's acotro / acotro_corecom / cscw / nrrm faces are FrontBase and this
-- script cannot read them.
-- ---------------------------------------------------------------------------

-- The schema is a LITERAL in the query below (the "target" CTE), not a
-- search_path setting -- SET search_path did not survive between statements in
-- Ken's client on 2026-08-29 and produced 58 false "missing table" rows.
--
-- Find the right value first if unsure:
--   SELECT n.nspname, count(*) FROM pg_class c
--   JOIN pg_namespace n ON n.oid = c.relnamespace
--   WHERE c.relkind='r' AND c.relname LIKE 'tb\\_%' GROUP BY 1 ORDER BY 2 DESC;
-- ============================================================================

WITH expected_tables(tbl, models) AS (VALUES
  {tbl_rows}
), expected_cols(tbl, col, models) AS (VALUES
  {col_rows}
), leftover_tables(tbl, migration, intended) AS (VALUES
  {left_rows}
), leftover_cols(tbl, col, migration) AS (VALUES
  {leftcol_rows}
), target AS (
  SELECT 'public'::text AS sch        -- <<<<<< EDIT ME.  Boise: fft_prod_bak2
), live_tables AS (
  SELECT t.table_name FROM information_schema.tables t, target
  WHERE t.table_schema = target.sch
), live_cols AS (
  SELECT c.table_name, c.column_name FROM information_schema.columns c, target
  WHERE c.table_schema = target.sch
), sanity AS (
  SELECT count(*) AS n FROM live_tables
)
-- Row 0 proves the schema is right. If tables_visible is 0 or absurdly low,
-- STOP: the schema literal is wrong and every row below it is meaningless.
SELECT '0 SCHEMA CHECK' AS finding,
       (SELECT sch FROM target) AS object,
       current_database() || ' :: ' || (SELECT n FROM sanity)::text || ' tables visible' AS detail
UNION ALL
SELECT '2 MISSING COLUMN', e.tbl || '.' || e.col, e.models
FROM expected_cols e JOIN live_tables t ON t.table_name = e.tbl
LEFT JOIN live_cols c ON c.table_name = e.tbl AND c.column_name = e.col
WHERE c.column_name IS NULL
UNION ALL
SELECT '1 MISSING TABLE', e.tbl, e.models
FROM expected_tables e LEFT JOIN live_tables t ON t.table_name = e.tbl
WHERE t.table_name IS NULL
UNION ALL
SELECT '3 NOT DROPPED/RENAMED', l.tbl, l.migration || ' :: ' || l.intended
FROM leftover_tables l JOIN live_tables t ON t.table_name = l.tbl
UNION ALL
SELECT '4 NOT DELETED', l.tbl || '.' || l.col, l.migration
FROM leftover_cols l JOIN live_cols c ON c.table_name = l.tbl AND c.column_name = l.col
ORDER BY 1, 2, 3;

-- Context, run separately:  SELECT * FROM "_DBUpdater" ORDER BY 1;
"""
out = pathlib.Path(sys.argv[2] if len(sys.argv) > 2 else "tb-schema-audit.sql")
out.write_text(sql)
print(f"{out}: {len(tables)} tables / {sum(len(c) for c in tables.values())} columns expected")
