#===== properties loadinfo : プロパティー・ロード
org.treasureboat.loadedApp.Properties.app=App

# Properties file for JavaMonitor
# Overrides the TBWebCore.framework Properties

TBLifebeatDestinationPort=1085
TBSessionTimeOut=1800
TBLifebeatEnabled=true
TBMonitorEnabled=true
TBAutoOpenInBrowser=true
TBCachingEnabled=true








er.extensions.ERXApplication.developmentMode=true







#30 minutes.


WODeploymentBackups=true



ERXRest.MHost.type.alias = osType

# Show the ModProxy tab.
er.javamonitor.showModProxyTab=true

# javamail
org.treasureboat.javamail.smtpHost=smpt.example.com

# Use Secure cookies (important for routeid in mod_proxy)
# er.extensions.ERXSession.useSecureProxyBalancerRouteCookies=true
# er.extensions.ERXSession.useSecureSessionCookies=true
er.extensions.ERXSession.useHttpOnlySessionCookies=true
